[tool.poetry]
name = "spectrexcel"
version = "1.0.2"
description = ""
authors = ["Alberto Mosconi <albertomaria.mosconi@gmail.com>"]
readme = "README.md"
package-mode = true
packages = [
{ include = "spectrexcel" }
]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
pyqt6 = "^6.7.1"
pandas = "^2.2.3"
xlsxwriter = "^3.2.0"
superqt = "^0.6.7"
pyinstaller = "^6.11.1"
pillow = "^11.0.0"
requests = "^2.32.5"
natsort = "^8.4.0"

[tool.poetry.scripts]
start = "spectrexcel.main:main"
build = "spectrexcel.pyinstaller:install"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
