[tool.poetry]
name = "spectrexcel"
version = "0.1.0"
description = ""
authors = ["Alberto Mosconi <albertomaria.mosconi@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
pyqt6 = "^6.7.1"
pandas = "^2.2.3"
xlsxwriter = "^3.2.0"
superqt = "^0.6.7"
pyinstaller = "^6.11.1"

[tool.poetry.scripts]
build = "spectrexcel.pyinstaller:install"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
