[project]
name = "spectrexcel"
version = "1.2.5"
description = ""
readme = "README.md"
requires-python = ">=3.10,<3.14"
license = { file = "LICENSE" }
authors = [
    { name = "Alberto Mosconi", email = "albertomaria.mosconi@gmail.com" },
]
dependencies = [
    "dearpygui>=2.3.1,<3",
    "natsort>=8.4.0,<9",
    "packaging>=25.0,<26",
    "pandas>=2.2.3,<3",
    "platformdirs>=4.3.8,<5",
    "requests>=2.32.5,<3",
    "xlsxwriter>=3.2.0,<4",
]

[project.scripts]
start = "spectrexcel.main:main"
build = "spectrexcel.pyinstaller:install"

[dependency-groups]
dev = [
    "pytest>=8.4.0,<10",
]
build = [
    "pyinstaller>=6.11.1,<7",
]

[tool.uv]
default-groups = ["dev", "build"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["spectrexcel"]
