"""Generated wrapper signatures for Dear PyGui 2.3.1.

Regenerate: uv run python scripts/generate_dearpygui_stubs.py
Native APIs retain their bundled signatures. Wrapper context managers return
context managers, nullable defaults remain nullable, and child slots 0-3 hold
lists. Deprecated wrappers retain their upstream replacement messages.
"""

from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Any, Literal, overload
from typing_extensions import deprecated as _deprecated

from dearpygui._dearpygui import *


def run_callbacks(jobs: Any) -> None: ...

def get_major_version() -> Any: ...

def get_minor_version() -> Any: ...

def get_dearpygui_version() -> Any: ...

def start_dearpygui() -> Any: ...

def mutex() -> AbstractContextManager[None]: ...

def popup(parent: int | str, mousebutton: int=..., modal: bool=..., tag: int | str=..., min_size: list[int] | tuple[int, ...]=..., max_size: list[int] | tuple[int, ...]=..., no_move: bool=..., no_background: bool=...) -> AbstractContextManager[int | str]: ...

def show_style_editor() -> None: ...

def show_metrics() -> None: ...

def show_about() -> None: ...

def show_debug() -> None: ...

def show_documentation() -> None: ...

def show_font_manager() -> None: ...

def show_item_registry() -> None: ...

def get_item_slot(item: int | str) -> int | None: ...

def is_item_container(item: int | str) -> bool | None: ...

def get_item_parent(item: int | str) -> int | None: ...

@overload
def get_item_children(item: int | str, slot: Literal[0, 1, 2, 3]) -> list[int]: ...
@overload
def get_item_children(item: int | str, slot: Literal[-1] = -1) -> dict[int, list[int]]: ...
@overload
def get_item_children(item: int | str, slot: int) -> dict[int, list[int]] | list[int] | None: ...

def get_item_type(item: int | str) -> str: ...

def get_item_theme(item: int | str) -> int: ...

def get_item_font(item: int | str) -> int: ...

def get_item_disabled_theme(item: int | str) -> int: ...

def enable_item(item: int | str) -> Any: ...

def disable_item(item: int | str) -> Any: ...

def set_item_label(item: int | str, label: str) -> Any: ...

def set_item_source(item: int | str, source: int | str) -> Any: ...

def set_item_pos(item: int | str, pos: list[float] | tuple[float, ...]) -> Any: ...

def set_item_width(item: int | str, width: int) -> Any: ...

def set_item_height(item: int | str, height: int) -> Any: ...

def set_item_indent(item: int | str, indent: int) -> Any: ...

def set_item_track_offset(item: int | str, offset: float) -> Any: ...

def set_item_payload_type(item: int | str, payload_type: str) -> Any: ...

def set_item_callback(item: int | str, callback: Callable[..., Any]) -> Any: ...

def set_item_drag_callback(item: int | str, callback: Callable[..., Any]) -> Any: ...

def set_item_drop_callback(item: int | str, callback: Callable[..., Any]) -> Any: ...

def track_item(item: int | str) -> Any: ...

def untrack_item(item: int | str) -> Any: ...

def set_item_user_data(item: int | str, user_data: Any) -> Any: ...

def show_item(item: int | str) -> Any: ...

def hide_item(item: int | str, *, children_only: bool=...) -> Any: ...

def get_item_label(item: int | str) -> str | None: ...

def get_item_filter_key(item: int | str) -> str | None: ...

def is_item_tracked(item: int | str) -> bool | None: ...

def get_item_indent(item: int | str) -> int | None: ...

def get_item_track_offset(item: int | str) -> float | None: ...

def get_item_width(item: int | str) -> int | None: ...

def get_item_height(item: int | str) -> int | None: ...

def get_item_callback(item: int | str) -> Callable | None: ...

def get_item_drag_callback(item: int | str) -> Callable | None: ...

def get_item_drop_callback(item: int | str) -> Callable | None: ...

def get_item_user_data(item: int | str) -> Any | None: ...

def get_item_source(item: int | str) -> str | None: ...

def is_item_hovered(item: int | str) -> bool | None: ...

def is_item_active(item: int | str) -> bool | None: ...

def is_item_focused(item: int | str) -> bool | None: ...

def is_item_clicked(item: int | str) -> bool | None: ...

def is_item_left_clicked(item: int | str) -> bool | None: ...

def is_item_right_clicked(item: int | str) -> bool | None: ...

def is_item_middle_clicked(item: int | str) -> bool | None: ...

def is_item_visible(item: int | str) -> bool | None: ...

def is_item_edited(item: int | str) -> bool | None: ...

def is_item_activated(item: int | str) -> bool | None: ...

def is_item_deactivated(item: int | str) -> bool | None: ...

def is_item_deactivated_after_edit(item: int | str) -> bool | None: ...

def is_item_toggled_open(item: int | str) -> bool | None: ...

def is_item_ok(item: int | str) -> bool | None: ...

def is_item_shown(item: int | str) -> bool | None: ...

def is_item_enabled(item: int | str) -> bool | None: ...

def get_item_pos(item: int | str) -> list[int]: ...

def get_available_content_region(item: int | str) -> list[int]: ...

def get_item_rect_size(item: int | str) -> list[int]: ...

def get_item_rect_min(item: int | str) -> list[int]: ...

def get_item_rect_max(item: int | str) -> list[int]: ...

def set_viewport_clear_color(color: list[int]) -> Any: ...

def set_viewport_small_icon(icon: str) -> Any: ...

def set_viewport_large_icon(icon: str) -> Any: ...

def set_viewport_pos(pos: list[float]) -> Any: ...

def set_viewport_width(width: int) -> Any: ...

def set_viewport_height(height: int) -> Any: ...

def set_viewport_min_width(width: int) -> Any: ...

def set_viewport_max_width(width: int) -> Any: ...

def set_viewport_min_height(height: int) -> Any: ...

def set_viewport_max_height(height: int) -> Any: ...

def set_viewport_title(title: str) -> Any: ...

def set_viewport_always_top(value: bool) -> Any: ...

def set_viewport_resizable(value: bool) -> Any: ...

def set_viewport_vsync(value: bool) -> Any: ...

def set_viewport_decorated(value: bool) -> Any: ...

def get_viewport_clear_color() -> list[int]: ...

def get_viewport_pos() -> list[float]: ...

def get_viewport_width() -> int: ...

def get_viewport_client_width() -> int: ...

def get_viewport_client_height() -> int: ...

def get_viewport_height() -> int: ...

def get_viewport_min_width() -> int: ...

def get_viewport_max_width() -> int: ...

def get_viewport_min_height() -> int: ...

def get_viewport_max_height() -> int: ...

def get_viewport_title() -> str: ...

def is_viewport_always_top() -> bool: ...

def is_viewport_resizable() -> bool: ...

def is_viewport_vsync_on() -> bool: ...

def is_viewport_decorated() -> bool: ...

def deprecated(reason: Any) -> Any: ...

@_deprecated("Use 'configure_app(init_file=file)'.")
def set_init_file(file: Any=...) -> Any: ...

@_deprecated("Use 'configure_app(init_file=file, load_init_file=True)'.")
def load_init_file(file: Any) -> Any: ...

@_deprecated('Use: `is_viewport_ok(...)`')
def is_viewport_created() -> Any: ...

@_deprecated('Use: \ncreate_viewport()\nsetup_dearpygui()\nshow_viewport()')
def setup_viewport() -> Any: ...

@_deprecated('Use: `bind_item_theme(...)`')
def set_item_theme(item: Any, theme: Any) -> Any: ...

@_deprecated('Use: `bind_item_type_disabled_theme(...)`')
def set_item_type_disabled_theme(item: Any, theme: Any) -> Any: ...

@_deprecated('Use: `bind_item_type_theme(...)`')
def set_item_type_theme(item: Any, theme: Any) -> Any: ...

@_deprecated('Use: `bind_item_font(...)`')
def set_item_font(item: Any, font: Any) -> Any: ...

@_deprecated('Use: `add_item_activated_handler(...)`')
def add_activated_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_active_handler(...)`')
def add_active_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_clicked_handler(...)`')
def add_clicked_handler(parent: Any, button: Any=..., **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_deactived_after_edit_handler(...)`')
def add_deactivated_after_edit_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_deactivated_handler(...)`')
def add_deactivated_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_edited_handler(...)`')
def add_edited_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_focus_handler(...)`')
def add_focus_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_hover_handler(...)`')
def add_hover_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_resize_handler(...)`')
def add_resize_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_toggled_open_handler(...)`')
def add_toggled_open_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_item_visible_handler(...)`')
def add_visible_handler(parent: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `bind_colormap(...)`')
def set_colormap(item: Any, source: Any) -> Any: ...

@_deprecated('Use: `bind_theme(0)`')
def reset_default_theme(item: Any, source: Any) -> Any: ...

@_deprecated('Deprecated by Dear PyGui.')
def set_staging_mode(mode: Any) -> Any: ...

@_deprecated('Deprecated by Dear PyGui.')
def add_table_next_column(**kwargs: Any) -> Any: ...

@_deprecated('Use: add_stage')
def add_staging_container(**kwargs: Any) -> Any: ...

@_deprecated('Use: stage')
def staging_container(**kwargs: Any) -> AbstractContextManager[int | str]: ...

@_deprecated('Use: add_spacer(...)')
def add_spacing(**kwargs: Any) -> Any: ...

@_deprecated('Use: add_spacer(...)')
def add_dummy(**kwargs: Any) -> Any: ...

@_deprecated('Use: `destroy_context()`')
def cleanup_dearpygui() -> Any: ...

@_deprecated('Use: group(horizontal=True)')
def add_same_line(**kwargs: Any) -> Any: ...

@_deprecated('Use: `get_plot_query_rects()`')
def is_plot_queried(plot: int | str, **kwargs: Any) -> Any: ...

@_deprecated('Use: `get_plot_query_rects()`')
def get_plot_query_area(plot: int | str, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_inf_line_series(horizontal=True)`')
def add_hline_series(x: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_inf_line_series()`')
def add_vline_series(x: Any, **kwargs: Any) -> Any: ...

@_deprecated('Use: `add_child_window()`')
def add_child(**kwargs: Any) -> Any: ...

@_deprecated('Use: `child_window()`')
def child(**kwargs: Any) -> AbstractContextManager[int | str]: ...

@_deprecated('Use: Just not recommended')
def setup_registries() -> None: ...

@_deprecated("Useless and doesn't work anyway")
def is_item_search_delayed(item: int | str) -> bool | None: ...

@_deprecated('Use: `set_frame_callback()`')
def set_start_callback(callback: Any) -> Any: ...

@_deprecated('This call is a no-op because character ranges are now automatic')
def add_font_chars(chars: list[int] | tuple[int, ...], *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., **kwargs: Any) -> int | str: ...

@_deprecated('This call is a no-op because character ranges are now automatic')
def add_font_range(first_char: int, last_char: int, *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., **kwargs: Any) -> int | str: ...

@_deprecated('This call is a no-op because character ranges are now automatic')
def add_font_range_hint(hint: int, *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., **kwargs: Any) -> int | str: ...

def child_window(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., height: int=..., indent: int=..., parent: int | str=..., before: int | str=..., payload_type: str=..., drop_callback: Callable[..., Any] | None=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., border: bool=..., autosize_x: bool=..., autosize_y: bool=..., no_scrollbar: bool=..., horizontal_scrollbar: bool=..., menubar: bool=..., no_scroll_with_mouse: bool=..., flattened_navigation: bool=..., always_use_window_padding: bool=..., resizable_x: bool=..., resizable_y: bool=..., always_auto_resize: bool=..., frame_style: bool=..., auto_resize_x: bool=..., auto_resize_y: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def clipper(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., indent: int=..., parent: int | str=..., before: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def collapsing_header(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., indent: int=..., parent: int | str=..., before: int | str=..., payload_type: str=..., drag_callback: Callable[..., Any] | None=..., drop_callback: Callable[..., Any] | None=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., closable: bool=..., default_open: bool=..., open_on_double_click: bool=..., open_on_arrow: bool=..., leaf: bool=..., bullet: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def colormap_registry(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def custom_series(x: list[float] | tuple[float, ...], y: list[float] | tuple[float, ...], channel_count: int, *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., before: int | str=..., source: int | str=..., callback: Callable[..., Any] | None=..., show: bool=..., y1: Any=..., y2: Any=..., y3: Any=..., tooltip: bool=..., no_fit: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def drag_payload(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., show: bool=..., drag_data: Any=..., drop_data: Any=..., payload_type: str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def draw_layer(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., before: int | str=..., show: bool=..., perspective_divide: bool=..., depth_clipping: bool=..., cull_mode: int=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def draw_node(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., before: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def drawlist(width: int, height: int, *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., before: int | str=..., callback: Callable[..., Any] | None=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def file_dialog(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., height: int=..., callback: Callable[..., Any] | None=..., show: bool=..., default_path: str=..., default_filename: str=..., file_count: int=..., modal: bool=..., directory_selector: bool=..., min_size: list[int] | tuple[int, ...]=..., max_size: list[int] | tuple[int, ...]=..., cancel_callback: Callable[..., Any] | None=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def filter_set(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., indent: int=..., parent: int | str=..., before: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def font(file: str, size: int, *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., pixel_snapH: bool=..., pixel_snapV: bool=..., parent: int | str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def font_registry(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def group(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., height: int=..., indent: int=..., parent: int | str=..., before: int | str=..., payload_type: str=..., drag_callback: Callable[..., Any] | None=..., drop_callback: Callable[..., Any] | None=..., show: bool=..., enabled: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., horizontal: bool=..., horizontal_spacing: float=..., xoffset: float=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def handler_registry(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def item_handler_registry(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def menu(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., indent: int=..., parent: int | str=..., before: int | str=..., payload_type: str=..., drop_callback: Callable[..., Any] | None=..., show: bool=..., enabled: bool=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def menu_bar(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., indent: int=..., parent: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def node(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., before: int | str=..., payload_type: str=..., drag_callback: Callable[..., Any] | None=..., drop_callback: Callable[..., Any] | None=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., draggable: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def node_attribute(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., indent: int=..., parent: int | str=..., before: int | str=..., show: bool=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., attribute_type: int=..., shape: int=..., category: str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def node_editor(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., height: int=..., parent: int | str=..., before: int | str=..., callback: Callable[..., Any] | None=..., show: bool=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., delink_callback: Callable[..., Any] | None=..., menubar: bool=..., minimap: bool=..., minimap_location: int=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def plot(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., height: int=..., indent: int=..., parent: int | str=..., before: int | str=..., payload_type: str=..., callback: Callable[..., Any] | None=..., drag_callback: Callable[..., Any] | None=..., drop_callback: Callable[..., Any] | None=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., no_title: bool=..., no_menus: bool=..., no_box_select: bool=..., no_mouse_pos: bool=..., query: bool=..., query_color: list[float] | tuple[float, ...]=..., min_query_rects: int=..., max_query_rects: int=..., crosshairs: bool=..., equal_aspects: bool=..., no_inputs: bool=..., no_frame: bool=..., use_local_time: bool=..., use_ISO8601: bool=..., use_24hour_clock: bool=..., pan_button: int=..., pan_mod: int=..., context_menu_button: int=..., fit_button: int=..., box_select_button: int=..., box_select_mod: int=..., box_select_cancel_button: int=..., query_toggle_mod: int=..., horizontal_mod: int=..., vertical_mod: int=..., override_mod: int=..., zoom_mod: int=..., zoom_rate: float=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def plot_axis(axis: int, *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., payload_type: str=..., drop_callback: Callable[..., Any] | None=..., show: bool=..., no_label: bool=..., no_gridlines: bool=..., no_tick_marks: bool=..., no_tick_labels: bool=..., no_initial_fit: bool=..., no_menus: bool=..., no_side_switch: bool=..., no_highlight: bool=..., opposite: bool=..., foreground_grid: bool=..., tick_format: str=..., scale: int=..., invert: bool=..., auto_fit: bool=..., range_fit: bool=..., pan_stretch: bool=..., lock_min: bool=..., lock_max: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def stage(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def subplots(rows: int, columns: int, *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., height: int=..., indent: int=..., parent: int | str=..., before: int | str=..., callback: Callable[..., Any] | None=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., row_ratios: list[float] | tuple[float, ...]=..., column_ratios: list[float] | tuple[float, ...]=..., no_title: bool=..., no_menus: bool=..., no_resize: bool=..., no_align: bool=..., share_series: bool=..., link_rows: bool=..., link_columns: bool=..., link_all_x: bool=..., link_all_y: bool=..., column_major: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def synced_tables(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., before: int | str=..., show: bool=..., filter_key: str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def tab(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., indent: int=..., parent: int | str=..., before: int | str=..., payload_type: str=..., drop_callback: Callable[..., Any] | None=..., show: bool=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., closable: bool=..., no_tooltip: bool=..., order_mode: int=..., unsaved_document: bool=..., no_close_with_middle_click: bool=..., no_reorder: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def tab_bar(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., indent: int=..., parent: int | str=..., before: int | str=..., callback: Callable[..., Any] | None=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., reorderable: bool=..., tab_list_popup_button: bool=..., no_close_with_middle_click: bool=..., no_scrolling_buttons: bool=..., no_tooltip: bool=..., draw_selected_overline: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def table(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., height: int=..., indent: int=..., parent: int | str=..., before: int | str=..., source: int | str=..., callback: Callable[..., Any] | None=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., header_row: bool=..., clipper: bool=..., inner_width: int=..., policy: int=..., freeze_rows: int=..., freeze_columns: int=..., sort_multi: bool=..., sort_tristate: bool=..., resizable: bool=..., reorderable: bool=..., hideable: bool=..., sortable: bool=..., context_menu_in_body: bool=..., row_background: bool=..., borders_innerH: bool=..., borders_outerH: bool=..., borders_innerV: bool=..., borders_outerV: bool=..., no_host_extendX: bool=..., no_host_extendY: bool=..., no_keep_columns_visible: bool=..., precise_widths: bool=..., no_clip: bool=..., pad_outerX: bool=..., no_pad_outerX: bool=..., no_pad_innerX: bool=..., scrollX: bool=..., scrollY: bool=..., no_saved_settings: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def table_cell(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., height: int=..., parent: int | str=..., before: int | str=..., show: bool=..., filter_key: str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def table_row(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., height: int=..., parent: int | str=..., before: int | str=..., show: bool=..., filter_key: str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def template_registry(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def texture_registry(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def theme(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def theme_component(item_type: int=..., *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., parent: int | str=..., before: int | str=..., enabled_state: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def tooltip(parent: int | str, *, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., show: bool=..., delay: float=..., hide_on_activity: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def tree_node(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., indent: int=..., parent: int | str=..., before: int | str=..., payload_type: str=..., drag_callback: Callable[..., Any] | None=..., drop_callback: Callable[..., Any] | None=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., filter_key: str=..., tracked: bool=..., track_offset: float=..., default_open: bool=..., open_on_double_click: bool=..., open_on_arrow: bool=..., leaf: bool=..., bullet: bool=..., selectable: bool=..., span_text_width: bool=..., span_full_width: bool=..., catch_nav_left: bool=..., lines: int=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def value_registry(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def viewport_drawlist(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., show: bool=..., filter_key: str=..., front: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def viewport_menu_bar(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., indent: int=..., parent: int | str=..., show: bool=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...

def window(*, label: str | None=..., user_data: Any=..., use_internal_label: bool=..., tag: int | str=..., width: int=..., height: int=..., indent: int=..., show: bool=..., pos: list[int] | tuple[int, ...]=..., min_size: list[int] | tuple[int, ...]=..., max_size: list[int] | tuple[int, ...]=..., menubar: bool=..., collapsed: bool=..., autosize: bool=..., no_resize: bool=..., unsaved_document: bool=..., no_title_bar: bool=..., no_move: bool=..., no_scrollbar: bool=..., no_collapse: bool=..., horizontal_scrollbar: bool=..., no_focus_on_appearing: bool=..., no_bring_to_front_on_focus: bool=..., no_close: bool=..., no_background: bool=..., modal: bool=..., popup: bool=..., no_saved_settings: bool=..., no_open_over_existing_popup: bool=..., no_scroll_with_mouse: bool=..., no_docking: bool=..., copy_contents_shortcut: bool=..., on_close: Callable[..., Any] | None=..., **kwargs: Any) -> AbstractContextManager[int | str]: ...
